# yaml-language-server: $schema=https://raw.githubusercontent.com/deepmap/oapi-codegen/HEAD/configuration-schema.json
package: apiclient
output: apiclient.gen.go
generate:
  models: true
  client: true
